name: laundry_scout
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  file_picker: ^10.1.9
  mime: ^1.0.5
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  geolocator: ^14.0.2 # Updated geolocator dependency
  permission_handler: ^11.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  http: ^1.1.0
  intl: ^0.20.2
  pdf: ^3.10.4
  printing: ^5.11.0
  geolocator_web: ^4.0.0 # Added geolocator_web dependency
  flutter_svg: ^2.0.10+1
  open_route_service: ^1.2.2
  image_gallery_saver: ^2.0.3
  universal_html: ^2.2.2
  image: ^4.5.4
  fl_chart: ^0.68.0
  url_launcher: ^6.2.5
  camera: ^0.10.5+9
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/lslogo.png
    - lib/assets/fb.png
    - lib/assets/google.png
    - .env
    - lib/assets/user/
    - lib/assets/user/owner.png
    - lib/assets/user/user.png
    - lib/assets/user/slides/
    - lib/assets/user/slides/first.png
    - lib/assets/user/slides/second.png
    - lib/assets/user/slides/third.png
    - lib/assets/promo_example.png
    - lib/assets/laundry_logo.svg
    - lib/assets/official.png
    - lib/assets/icons/laundry-machine.svg
    - lib/assets/icons/filter.png
    - lib/assets/orders/pickup.png
    - lib/assets/orders/orders.png
    - lib/assets/orders/delivery.png
    - lib/assets/navbars/home.png
    - lib/assets/navbars/location.png
    - lib/assets/navbars/laundry.png
    - lib/assets/navbars/message.png
    - lib/assets/navbars/notification.png
    - lib/assets/owner/
    - lib/assets/owner/reviews.png
    - lib/assets/owner/reports.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/font/Poppins-Regular.ttf
        - asset: lib/assets/font/Poppins-Bold.ttf
          weight: 700
        # Add other weights and styles of Poppins you intend to use
        # e.g.:
        # - asset: assets/fonts/Poppins-SemiBold.ttf
        #   weight: 600
        # - asset: assets/fonts/Poppins-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/Poppins-Light.ttf
        #   weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: lib/assets/lslogo.png
