name: laundry_scout
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.4  # Add this line
  flutter_dotenv: ^5.1.0    # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/lslogo.png
    - lib/assets/fb.png
    - lib/assets/google.png
    - lib/assets/apple.png
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/font/Poppins-Regular.ttf
        - asset: lib/assets/font/Poppins-Bold.ttf
          weight: 700
        # Add other weights and styles of Poppins you intend to use
        # e.g.:
        # - asset: assets/fonts/Poppins-SemiBold.ttf
        #   weight: 600
        # - asset: assets/fonts/Poppins-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/Poppins-Light.ttf
        #   weight: 300
